Jayden cesar validate info
BroncoHacks-Website/Application-Portal pull request #43
Opened 2024-03-19 20:25 UTC by Jay7vn

2024-03-19 20:46 UTC, christopherjlo commented
Please DM me on discord with the contents of your .env file since it's not pushed in the repo (which is correct).
Also, currently database.js has code that looks like a merge didn't finish in the web editor (starting with <<<< HEAD), please fix and commit again.

2024-03-19 20:47 UTC, christopherjlo commented on server/config/database.js
Pls fix line 5 - 15

2024-03-19 20:47 UTC, christopherjlo requested changes
see comment on database.js

2024-03-19 21:25 UTC, christopherjlo approved these changes

2024-03-19 21:30 UTC, christopherjlo commented
# DO NOT MERGE THIS PR YET

@chillwafflez @DanielPasion we need to discuss and standardize controllers and routes before merging anything cuz otherwise merging will get really messy

2024-03-20 01:10 UTC, DanielPasion commented
> # DO NOT MERGE THIS PR YET
> @chillwafflez @DanielPasion we need to discuss and standardize controllers and routes before merging anything cuz otherwise merging will get really messy



> Please DM me on discord with the contents of your .env file since it's not pushed in the repo (which is correct). Also, currently database.js has code that looks like a merge didn't finish in the web editor (starting with <<<< HEAD), please fix and commit again.

Caleb specified what the .env files were already for the env file its the aws setup stuff.

2024-04-02 22:03 UTC, MichaelWuhu commented
I added password hashing (for create acc route) and moved some stuff around to fit what the tech leads chose to standardize. 

Make sure that everythin works as it shuld (i used the name 'userLogin' for most things related to this task) and then delete any old/unused files/commets/folders then re-ping a tech lead to see if we can merge this into main

don't forget to run 'npm install' before u start testing
(also i did have to change up ur guys' package.json so you might need to delete all node modules then rerun 'npm install')

@Jay7vn @cesar-henry

2024-04-08 03:59 UTC, closed without merging